#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ntp'
cookbook 'openssh'
cookbook 'chef-client'

cookbook 'apt',
  :git => 'https://github.com/mattray/apt.git'
